Document: yaamake
Title: Debian yaamake Manual
Author: <insert document author here>
Abstract: This manual describes what yaamake is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yaamake/yaamake.sgml.gz

Format: postscript
Files: /usr/share/doc/yaamake/yaamake.ps.gz

Format: text
Files: /usr/share/doc/yaamake/yaamake.text.gz

Format: HTML
Index: /usr/share/doc/yaamake/html/index.html
Files: /usr/share/doc/yaamake/html/*.html
